[package]
name = "vadersay"
version = "0.1.0"
authors = ["prof79 <markus@markusegger.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.17"
